%YAML:1.0
#=====================================打符识别部分=====================================#

#====取图蒙板参数====#
#蒙板左上角相对x坐标倍数，范围0～1，TL即Left Top
mask_TL_x: 0.0
#蒙板左上角相对y坐标倍数，范围0～1，TL即Left Top
mask_TL_y: 0.0
#蒙板矩形相对宽度倍数，范围0～1-mask_TL_x
mask_width: 1.0
#蒙板矩形相对高度倍数，范围0～1-mask_TL_y
mask_height: 1.0

#======滤波开关======#
#是否开启高斯滤波，0为关闭，1为开启
switch_gaussian_blur: 0

#======UI开关======#
switch_UI_contours: 1
switch_UI_areas: 1
switch_UI: 1


#R最小面积
s_R_min: 200 #300
#R最大面积
s_R_max: 800 #750
#R最小长宽比(长/宽)
R_ratio_min: 0.7   #0.7
#R最大长宽比(长/宽)
R_ratio_max: 1.5 #1.5
#R最小面积比(轮廓面积/最小外包矩形面积)
s_R_ratio_min: 0.25  #0.5
#R最大面积比(轮廓面积/最小外包矩形面积)
s_R_ratio_max: 1.7 #1.7
#R最小圆度
R_circularity_min: 0.1 #0.5
#R最大圆度
R_circularity_max: 0.9 #0.9
#R最小紧致度
R_compactness_min: 12 #14
#R最大紧致度
R_compactness_max: 60 #27
#扇页最小面积
s_wing_min: 1000
#扇页最大面积
s_wing_max: 1400
#扇页最小长宽比(长/宽)
wing_ratio_min: 1.4
#扇页最大长宽比(长/宽)
wing_ratio_max: 5.5
#扇页最小面积比(轮廓面积/最小外包矩形面积)
s_wing_ratio_min: 0.2
#扇页最大面积比(轮廓面积/最小外包矩形面积)
s_wing_ratio_max: 3.0
#扇页上半部分最小面积
s_winghat_min: 200
#扇页上半部分最大面积
s_winghat_max: 500
#扇页上半部分最小长宽比(长/宽)
winghat_ratio_min: 1.7
#扇页上半部分最大长宽比(长/宽)
winghat_ratio_max: 3.8
#扇页上半部分最小面积比(轮廓面积/最小外包矩形面积)
s_winghat_ratio_min: 0.15
#扇页上半部分最大面积比(轮廓面积/最小外包矩形面积)
s_winghat_ratio_max: 0.4
#能量机关半径 mm
R: 700
#能量机关实际宽度
length: 0.68
#云台标准位置离R高度
hight: 1.2
#打击点距能量机关R水平距离
hit_dx: 6.50
#匀速转动角速度（小符）
constant_speed: 60.0
# 是否逆时针转动 1是-1不是
direction: 1
#空气摩擦系数
init_k_: 0.02
#速度函数参数
A: 0.912
w: 1.942
fai: 0.0
#膨胀操作参数
#第一次膨胀的参数
dialte1: 1
#第二次膨胀的参数
dialte2: 1.0
#第三次膨胀的参数
dialte3: 1.0
#预测偏置参数
re_time: 0.21 #0.06~0.1约等于半个装甲板
#二值化阈值
#二值化最小值
thb:  60.0
#二值化最大值
tht:  108.0 #108

#===R感兴趣区域===#
#左边界倍率
R_roi_xl: 0.28
#上边界倍率
R_roi_yt: 0.65
#右边界倍率
R_roi_xr: 0.415
#下边界倍率
R_roi_yb: 0.37
#时间、速度、角速度队列的大小
list_size: 120

fake_pitch: 0.0
fake_yaw: 0.0
fake_bullet_v: 250.0
fake_status: 0
fake_now_time: 0
fake_predict_time: 0

#=====================================hsv数据=====================================#
hmin: 80
hmax: 135 #101 #124
smin: 0 #36
smax: 255
vmin: 160 #46 
vmax: 255
e_hmin: 0
e_hmax: 30
e_smin: 119
e_smax: 255
e_vmin: 80
e_vmax: 255
